// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXS-QeBzR9WO8D8RxQIztmtnGILdGjGO4',
    appId: '1:953330828039:web:07cf6555a8c99157273ba2',
    messagingSenderId: '953330828039',
    projectId: 'ecommerce-app-1ea1d',
    authDomain: 'ecommerce-app-1ea1d.firebaseapp.com',
    storageBucket: 'ecommerce-app-1ea1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANlA90n_FWeyeF20LN624ZfMnDjxWjHkU',
    appId: '1:953330828039:android:f6ae1b055ecd024d273ba2',
    messagingSenderId: '953330828039',
    projectId: 'ecommerce-app-1ea1d',
    storageBucket: 'ecommerce-app-1ea1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbq9V2ImqnziFagRUxeigc8HsFMeCh-k',
    appId: '1:953330828039:ios:dd49b57c12dd7abf273ba2',
    messagingSenderId: '953330828039',
    projectId: 'ecommerce-app-1ea1d',
    storageBucket: 'ecommerce-app-1ea1d.firebasestorage.app',
    iosBundleId: 'com.example.officeProject',
  );
}
